### ISSUE TITLE
Bug reports and suggestions

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#12]
So many update 'o'

Wonderful job (the new kinetic blast rocks!) so far 👍 

I tested quite everything I could think of so here it comes : 

1. Perhaps not a bug : none of your new infusions/wild talents can be selected with Truinto's DarkCodex Extra Wild Talent feat, but Aether can be selected with Extra Element feat.

2. More of a cosmetic issue, but would be great for information : none of the force blast tooltip actually display the damage of the blast beforehand, while kinetic blast, as any other, does (I have some sreen if you want).

3. Foe Throw damage type/calculation : as of now Foe Throw does force damage to both targets, when it should do slice/etc..., and the damage calculation seems wrong since it should do as much damage as the base telekinetic one (1d6+1 per two level + Stat mod + overflow ) -> as of now it does only Xd6 + X damage.

4. Many Throw telekinetic damage also seems to be miscalculated seens it only does Xd6 damage (+ overflow perhaps but cannot be sure since I cannot correctly break down damage log) when it should do the full physic basic blast.

_Did not run into bugs with Force hook or Disintegrate infusion so far (well, considering the the current Disintegrate state)._

On top of this, more for balance purpose, I would suggest three things : 

1. Many Throws to be usable with force blast, which sorely lacks multiple target infusion (bare wall).

2. Up force blast damage to classic composite energy blast same as blue fire (already suggested but to be complete^^).

3. Concerning Telekinetic Finesse, I think it could provide an untyped/special bonus to trickery, such as +1/2 kineticist level, since ingame it lacks utility that only exists in TT.

Really excited for this !

PS : and sorry I'm nothing of a native english speaker so I can be quite blunt and grammaticaly approximate...

**Comment by Mythalar** [comment]
And a question : do you have implemented the size restriction with Foe Throw? And if so how does it work? 
(I only tested it on the centipedes at the beginning of the game)
Does it work with pushing/substance infusion?

**Comment by SpencerMycek** [comment]
Hey, thank you for calling these out, let's answer down the list:
Bugs: 
1. I had to specifically add the Wild Talents to the Extra Wild Talent feature (Fixed)
2. I honestly have no idea how the game determines what to put on the tooltip, I might have to dig further (not fixed)
3. Fixed now, I forgot to add the second half of what adds that extra +1 per die (And now added to Elemental Overflow)
4. Fixed as well, same issue as above :)

Suggestions:
1. Many Throw, I believe, is a lot better than every other AOE infusion, since it has the potential to hit the entire battle with the full damage of the blast, I want to hold off on giving Force Blast access because
2. Force blast now does full composite damage, it's the only instance of "Composite does simple damage" that I can think of, and the reasoning is essentially negated by Ascended Element
3. I was thinking that RangedLegerdemain (Arcane Trickster and Telekinetic Finesse) don't really do much in this game, as you can reach most traps without them. So I did add 1/2 kineticist level to scaling

Honestly, I want to add Many Throw to Force, but add the current moment, doing 16d6+Elemental Overflow Force to almost all enemies (tested at level 15, so 16d6 and 15 targets), is pretty nuts, but I haven't been able to actually finish WoTR myself, so maybe it's not as bad as an issue as I think. But I'll wait and see if Force Blast really needs it

**Comment by Mythalar** [comment]
Oh this is all nice and so quickly fixed !

Tested and no issue so far (perhaps the trickery bonus should be added to the description).

As for the Many throw discussion : I quite agree with you, but as an example an Angel divine caster would, with a 8th Strom of justice, deal 1d6 points of holy damage per caster level (target needs to make a successful Reflex saving throw, or become prone), and if the target is evil, the spell instead deals 1d8 points of holy damage per caster level ( + full effect of [Bolt of ustice spell](url=https://pathfinderwrathoftherighteous.wiki.fextralife.com/Bolt+of+Justice), and with merged spell book you can cast it as soon as lvl 11 (I think), and **does no need any attack roll.**

Quite the same thing for Lich, Trickster and Vital strike is worse etc...

On the other hand there are very few mythic abilities that add something to kinetic blasts (if memory serves just one Liche power) so it's not really brokken.

But I love arguing so... ;)
