### ISSUE TITLE
Bug Report : Telekinetic finesse bonus skill

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#16]
Hey, as of now I cannot see any Trickery bonus on my character sheet from Telekinetic finesse but I do see the bonus from Skilled kineticist.

I tried disabling/enabling the ability, if it's tied to its actual use, but to no avail.

**Comment by SpencerMycek** [comment]
Not sure what the issue might be: 
![image](https://user-images.githubusercontent.com/32203066/176777016-2bf90ccf-8990-4a9d-998e-c58c29ebff05.png)
![image](https://user-images.githubusercontent.com/32203066/176777104-5d069811-0368-4fdc-b71d-9228941f2981.png)

--> Level 12 test character
Appears to be working, but it may be because you've had the ability since before the update that changed it. If you respec and reselect the ability, it should work fine

**Comment by Mythalar** [comment]
Weird, I'll look into it

**Comment by Mythalar** [comment]
Yep that must be it I'm dumb...

I loaded a save that was probably older that the addition and I had already the wild feat.

It works on a new one, when I actually use the ability.

**Comment by SpencerMycek** [comment]
No worries, I had the same issues testing infusions
