### ISSUE TITLE
Suggestion: Some icons for a couple of the abilites

### ISSUE THREAD

**Issue by Adsam112** [SpencerMycek/KineticistExpandedElements#25]
Just made these in Photoshop, thought they fit the look of the blasts

Emptiness:
![Emptyness](https://user-images.githubusercontent.com/49521120/179367663-f4051c0c-a237-49c5-bc96-fa5e46177dfb.png)

Gravity Blast:
![Gravity Blast](https://user-images.githubusercontent.com/49521120/179367726-a12c056b-6472-4b2c-b964-31739b62fee6.png)

Negative Blast:
![Negative Blast](https://user-images.githubusercontent.com/49521120/179367740-5cb769bb-65b9-4bd2-97f7-f9d6f4ab2c9f.png)
 
Void Blast:
![Void Blast](https://user-images.githubusercontent.com/49521120/179367756-5507d103-bf4a-4782-9c3d-a9873d0fda3b.png)

Also I assume the current blasts fx are fillers. If someone manages to make more fitting purple fx i Imagine these would still fit just make them purple.

**Comment by SpencerMycek** [comment]
These are amazing, TY so much (Gotta learn how to add my own icons now, but that's nothing)

These are really great. I was honestly just looking for random abilities to steal icons from, but thank you so much

**Comment by RevanStarforge** [comment]
and i just made these for more purplish option..?

![1](https://user-images.githubusercontent.com/90949662/179522073-3cf75b4d-b849-46a9-a7ef-f280d981eec4.png)


![2](https://user-images.githubusercontent.com/90949662/179522108-5ff3dc06-1a9f-4da6-a3bd-7d49657db960.png)


![3](https://user-images.githubusercontent.com/90949662/179522127-70d51c7b-d6de-4a64-9d80-18ec45745b8d.png)


This would looks fitting for gravity blast in my opinion..?
![4](https://user-images.githubusercontent.com/90949662/179522150-675e9cba-912e-4b57-9c9c-c9ee17fbce11.png)



my suggestion for Negative Blast;
![4 - Kopya](https://user-images.githubusercontent.com/90949662/179527125-0584a43c-3208-4556-82e2-d2c2fe8f4e70.png)

and maybe this for Void... i know it's very plain, and dark... but sort of i thought it would be the point..? since it's... void
![4 - Kopya](https://user-images.githubusercontent.com/90949662/179527916-25121473-e63b-46b8-a142-74550727da56.png)

**Comment by SpencerMycek** [comment]
Man I now have a ton of fun options, I'll test a few out and see what I thing fits best in the game. But thank you both!

**Comment by SpencerMycek** [comment]
Thank you for these, we'll be able to find this issue later for the icons. But I'm going to close it for clutter
